export const ADD_INGREDIENT = 'APP.ADD_INGREDIENT';
export const REMOVE_INGREDIENT = 'APP.REMOVE_INGREDIENT';
export const UPDATE_INGREDIENT = 'APP.UPDATE_INGREDIENT';

export const SELECT_TECHNIQUE = 'APP.SELECT_TECHNIQUE';

export const SELECT_UNIT = 'APP.SELECT_UNIT';
