export const FETCH_AVAILABLE = 'TECHNIQUE.FETCH_AVAILABLE';
export const FETCH_AVAILABLE_SUCCESS = 'TECHNIQUE.FETCH_AVAILABLE_SUCCESS';
export const FETCH_AVAILABLE_ERROR = 'TECHNIQUE.FETCH_AVAILABLE_ERROR';

export const RECEIVE_AVAILABLE = 'TECHNIQUE.RECEIVE_AVAILABLE';

export const UPDATE_SELECTED = 'TECHNIQUE.UPDATE_SELECTED';
