export const DECREMENT_OUTSTANDING_REQUESTS = 'DECREMENT_OUTSTANDING_REQUESTS';
export const INCREMENT_OUTSTANDING_REQUESTS = 'INCREMENT_OUTSTANDING_REQUESTS';

export const RECEIVE_AVAILABLE_INGREDIENTS = 'RECEIVE_AVAILABLE_INGREDIENTS';
export const FETCH_AVAILABLE_INGREDIENTS_SUCCESS = 'FETCH_AVAILABLE_INGREDIENTS_SUCCESS';
export const FETCH_AVAILABLE_INGREDIENTS_ERROR = 'FETCH_AVAILABLE_INGREDIENTS_ERROR';
export const FETCH_AVAILABLE_INGREDIENTS = 'FETCH_AVAILABLE_INGREDIENTS';

export const LIST_SELECTED_INGREDIENTS = 'LIST_SELECTED_INGREDIENTS';
