export const FETCH_AVAILABLE = 'INGREDIENT.FETCH_AVAILABLE';
export const FETCH_AVAILABLE_SUCCESS = 'INGREDIENT.FETCH_AVAILABLE_SUCCESS';
export const FETCH_AVAILABLE_ERROR = 'INGREDIENT.FETCH_AVAILABLE_ERROR';

export const RECEIVE_AVAILABLE = 'INGREDIENT.RECEIVE_AVAILABLE';

export const ADD_MEASUREMENT = 'INGREDIENT.ADD_MEASUREMENT';
export const UPDATE_MEASUREMENT = 'INGREDIENT.UPDATE_MEASUREMENT';
export const REMOVE_MEASUREMENT = 'INGREDIENT.REMOVE_MEASUREMENT';

export const WHITELIST_TAGS = [ 'a', 'em', 'strong' ];
