export const FETCH_AVAILABLE = 'INGREDIENT.FETCH_AVAILABLE';
export const FETCH_AVAILABLE_SUCCESS = 'INGREDIENT.FETCH_AVAILABLE_SUCCESS';
export const FETCH_AVAILABLE_ERROR = 'INGREDIENT.FETCH_AVAILABLE_ERROR';

export const RECEIVE_AVAILABLE = 'INGREDIENT.RECEIVE_AVAILABLE';

export const UPDATE_SELECTED = 'INGREDIENT.UPDATE_SELECTED';
